#!/bin/bash

git checkout master    
git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done #set tracking of all remote branches
git fetch --all # fetch all remote branches to the local repository
git pull --all # update all local branches
for BRANCH in `git branch --list | sed 's/\*//g'`
do
    COMMITS_AHEAD_OF_MASTER=`git log master..$BRANCH`
    if [ -z "$COMMITS_AHEAD_OF_MASTER" ]
    then
        COMMITS_BEHIND_MASTER=`git log $BRANCH..master`
        if [ -z "$COMMITS_BEHIND_MASTER" ]
        then
            echo $BRANCH >> up_to_date.txt
        else
            echo $BRANCH >> behind.txt
        fi
    else
        echo $BRANCH >> ahead.txt
    fi
done
